In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

In [10]:
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [11]:
features = df.columns[1:-1]
print(features)

Index(['sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')


In [ ]:
ig,axs = plt.subplots(nrows=3, ncols=4, figsize=(16,12))
for i, feature in enumerate(features):
    row, col = 1//4, i%4
    sns.regplot(x=feature, y=diabetes.target, data=df, ax=axs[row][col])

In [ ]:
from sklearn.mo

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
y = diabetes.target
X = df['age'].values.reshape(-1,1)
lr = LinearRegression()
lr.fit(X,y)
lr.score(X,y)

0.03530218264671647

In [16]:
y = diabetes.target
for feature in diabetes.feature_names:
    X = df[feature].values.reshape(-1,1)
    lr=LinearRegression()
    lr.fit(X,y)
    r2 = lr.score(X,y)
    print(f'{feature}: \t{r2:.4f}')

age: 	0.0353
sex: 	0.0019
bmi: 	0.3439
bp: 	0.1949
s1: 	0.0450
s2: 	0.0303
s3: 	0.1559
s4: 	0.1853
s5: 	0.3202
s6: 	0.1463


In [17]:
X = diabetes.data
y = diabetes.target
lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [18]:
lr.score(X, y)

0.5177494254132934

In [19]:
lr.coef_

array([ -10.01219782, -239.81908937,  519.83978679,  324.39042769,
       -792.18416163,  476.74583782,  101.04457032,  177.06417623,
        751.27932109,   67.62538639])

In [20]:
lr.intercept_

152.1334841628965

In [22]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [23]:
np.dot(lr.coef_, diabetes.data[0]) + lr.intercept_

206.1170697870923

In [24]:
for i in range(5):
    pred = np.dot(lr.coef_, diabetes.data[i]) + lr.intercept_
    print(f'예측값: {pred: 2f}, 실제값: {diabetes.target[i]}')

예측값:  206.117070, 실제값: 151.0
예측값:  68.072348, 실제값: 75.0
예측값:  176.884060, 실제값: 141.0
예측값:  166.917966, 실제값: 206.0
예측값:  128.459842, 실제값: 135.0


In [25]:
lr.predict(diabetes.data[:5])

array([206.11706979,  68.07234761, 176.88406035, 166.91796559,
       128.45984241])

In [26]:
lr.predict(diabetes.data[0:1]), lr.predict(diabetes.data[0].reshape(1,-1))

(array([206.11706979]), array([206.11706979]))