# 평가

-MINIST 손글씨 "Is it seven?"

In [17]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [18]:
digits = load_digits()
digits.data.shape

(1797, 64)

In [19]:
digits.data[1655]

array([ 0.,  0.,  8., 16., 16., 12.,  0.,  0.,  0.,  0., 16., 13., 10.,
       16.,  3.,  0.,  0.,  0., 12.,  1.,  2., 16.,  4.,  0.,  0.,  0.,
        0.,  0.,  6., 15.,  0.,  0.,  0.,  0.,  0.,  1., 15., 10.,  0.,
        0.,  0.,  0.,  0.,  9., 15.,  2.,  0.,  0.,  0.,  1., 11., 16.,
       12.,  8.,  8.,  1.,  0.,  0., 11., 16., 16., 16., 12.,  1.])

In [20]:
from sklearn.base import BaseEstimator

class MyFakeClassfier(BaseEstimator):
    def fit(self, X, y):
        pass
    def predict(self, X):
        return np.zeros(X.shape[0], dtype=int)

In [21]:
X = digits.data
y = (digits.target == 7).astype(int)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,y, stratify=y, test_size=0.2, random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1437, 64), (360, 64), (1437,), (360,))

In [23]:
np.unique(y_train, return_counts=True)

(array([0, 1]), array([1294,  143], dtype=int64))

- Decision Tree 분류기

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train, y_train)
pred_dt = dtc.predict(X_test)

In [25]:
myc = MyFakeClassfier()
myc.fit(X_train, y_train)
pred_my = myc.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred_my)

0.9

- 오차 행렬

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred_dt)

array([[317,   7],
       [  7,  29]], dtype=int64)

In [29]:
confusion_matrix(y_test, pred_my)

array([[324,   0],
       [ 36,   0]], dtype=int64)