In [91]:
import numpy as np
import pandas as pd

In [92]:
df = pd.read_csv('ThoraricSurgery.csv', header=None)
df.head()

0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0  293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   0
1    1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   0
2    8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   1
3   14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   1
4   17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   0

In [93]:
df[17].value_counts()

0    400
1     70
Name: 17, dtype: int64

- 데이터 분리

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,:-1].values, df[17].values, stratify=df[17].values, test_size=0.2, random_state=2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((376, 17), (94, 17), (376,), (94,))

- 모델생성, 학습

In [99]:
from sklearn.tree import DecisionTreeClassifier
rfc = DecisionTreeClassifier(random_state=2021)

In [102]:
rfc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2021)

In [103]:
pred_rf = rfc.predict(X_test)

In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score
confusion_matrix(y_test, pred_rf)

array([[61, 19],
       [11,  3]], dtype=int64)

In [119]:
rfc.score(X_test, y_test), recall_score(y_test, pred_rf)

(0.6808510638297872, 0.21428571428571427)

In [120]:
from sklearn.model_selection import GridSearchCV
params = {
    'max_depth': [2,3,4,5,6],
    'min_samples_split': [2,3,4]
}

In [121]:
grid_rf = GridSearchCV(rfc, param_grid=params, scoring='accuracy', cv=3)
grid_rf.fit(X_train, y_train)
grid_rf.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [122]:
pred_grid = grid_rf.best_estimator_.predict(X_test)
confusion_matrix(y_test, pred_grid)

array([[77,  3],
       [13,  1]], dtype=int64)

In [123]:
pred_grid = grid_rf.best_estimator_.predict(X_test)
confusion_matrix(y_test, pred_grid)

array([[77,  3],
       [13,  1]], dtype=int64)

In [124]:
accuracy_score(y_test, pred_rf), recall_score(y_test, pred_rf)

(0.6808510638297872, 0.21428571428571427)

In [125]:
from sklearn.model_selection import GridSearchCV
params = {
    'max_depth': [2,3,4,5,6],
    'min_samples_split': [2,3,4]
}

In [126]:
grid_rf = GridSearchCV(rfc, param_grid=params, scoring='accuracy', cv=3)
grid_rf.fit(X_train, y_train)
grid_rf.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [127]:
pred_grid = grid_rf.best_estimator_.predict(X_test)
confusion_matrix(y_test, pred_grid)

array([[77,  3],
       [13,  1]], dtype=int64)

In [128]:
grid_rf2 = GridSearchCV(rfc, param_grid=params, scoring='recall', cv=3)
grid_rf2.fit(X_train, y_train)
grid_rf2.best_params_

{'max_depth': 6, 'min_samples_split': 4}

In [129]:
pred_grid2 = grid_rf2.best_estimator_.predict(X_test)
confusion_matrix(y_test, pred_grid2)

array([[72,  8],
       [13,  1]], dtype=int64)

In [130]:
from sklearn.svm import SVC
svc = SVC(random_state=2021)
svc.fit(X_train, y_train)
pred_svc = svc.predict(X_test)
confusion_matrix(y_test, pred_svc)

array([[80,  0],
       [14,  0]], dtype=int64)

In [131]:
svc.predict(X_test[10].reshape(1,-1))

array([0], dtype=int64)

In [132]:
y_test[10]

0